#!/usr/bin/env python3.6

import os
import sys
import hashlib
import logging
import argparse
import math

from collections import defaultdict

from find_duplicate_files import find_duplicate_files, parse_cmd_args


if __name__ == '__main__':
    from pprint import pprint

    args = parse_cmd_args(sys.argv[1:])

    duplicates = find_duplicate_files(args.dir, args.chunk)
    print("Duplicate files found in %s -" % args.dir)
    pprint(duplicates)
